export const GET_PLANS = 'GET_PLANS'
export const GET_USERS = 'GET_USERS'
export const CREATE_USER = 'CREATE_USER'
export const CREATE_CALC = 'CREATE_CALC'
export const CHANGE_DONE = 'CHANGE_DONE'
export const GO_PUSH = 'GO_PUSH'
